# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fad8780608e64c006d7f8cacaa68423ce597c077c90560d6a81230dba59810d8967997e65ac61fd5acbb9e2fc2275dded033d346b35b6410da960df7d377b99d

test:
  secret_key_base: f1d50b2449819a26cb81f63abd7a4c75fb11a9b5e8026cf4860977816176166058e54ffcc02813bbacd0040d02d27545d8d7e6d450e271bad664836dc92477a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
